### ISSUE TITLE
Root store pattern

### ISSUE THREAD

**Issue by bfeeley** [mobxjs/mobx-react-docz#42]
I'm curious ... using, this new context approach ... is a root store pattern with multiples stores attached still advisable, and if so, are there any examples anywhere?

**Comment by FredyC** [comment]
It is advisable. In fact, the previous `Provider/inject` did the same, all stores were sitting at a single root object, it has just hidden such detail from you. Now you have the choice do it either way. You can have a root which you will be accessing or you can make yourself a hook that will give you a store by a string name from that root. There is no special magic about it really :)

Or you can consider mobx-state-tree for more complex needs.

There are no examples at the moment. Mainly because the way of managing stores is not exactly in the scope of mobx-react libraries. It's completely up to your preferences.

**Comment by bfeeley** [comment]
Awesome! Thanks @FredyC. Would it be as simple as this (this is super basic for brevity sake :-) ):

`
  import SubStore from '/subStore';

  export const createStore = () => {
    const store = {
      subStore: SubStore,
      ...
    };

    return store;
});

export type TStore = ReturnType<typeof createStore>`

More or less? And thanks for this library!!!

**Comment by FredyC** [comment]
If `SubStore` is a class-based store you probably want `new SubStore()` but yea, otherwise it's just fine like that. It also gives you nice power over dependencies between stores. If one would depend on another, you can pass it through the constructor here and it's a win.
